In [167]:
import os
import torch
from pathlib import Path
!pip install xarray netCDF4
import xarray
import netCDF4
HOME = Path.home()
print("using home dir:", HOME)

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

print("\nCuda is available: "+str(torch.cuda.is_available()))

!nvcc --version

Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
using home dir: /home/ec2-user
Thu Jun  8 23:13:26 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         On   | 00000000:00:1E.0 Off |                    0 |
|  0%   30C    P8    20W / 300W |      2MiB / 23028MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+--------------------

In [168]:
# download data from s3
import boto3
import netCDF4
import os
import boto3
import sagemaker
import xarray as xr
import pandas as pd
from pathlib import Path
HOME=Path.home()
%alias mkdatadir mkdir -p %l
sess = sagemaker.Session()
bucket = sess.default_bucket()                    # Set a default S3 bucket
print(f"Using s3 bucket: {bucket}")
DATA_DIR=f"{HOME}/SageMaker/data_downloads"
MODEL_DATA=f"{HOME}/SageMaker/model_data"
print(f"Using download data path: {DATA_DIR}")
print(f"Using model data path: {DATA_DIR}")
%mkdatadir $DATA_DIR

Using s3 bucket: sagemaker-us-west-2-014690315417
Using download data path: /home/ec2-user/SageMaker/data_downloads
Using model data path: /home/ec2-user/SageMaker/data_downloads


In [169]:
# download the data from s3


def sync_s3_to_local(bucket_name, prefix, local_directory):
    s3 = boto3.client('s3')

    # List all objects in the bucket with the specified prefix
    response = s3.list_objects_v2(Bucket=bucket_name, Prefix=prefix)
    objects = response['Contents']

    # Sync each object to the local directory
    for obj in objects:
        key = obj['Key']
        local_path = os.path.join(local_directory, key)

        # Create the local directory if it doesn't exist
        os.makedirs(os.path.dirname(local_path), exist_ok=True)

        # Check if the local file already exists
        if os.path.exists(local_path):
            print(f"Skipping {key} (already exists)")
            continue

        # Download the object from S3 to the local directory
        s3.download_file(bucket_name, key, local_path)
        print(f"Downloaded {key}")

# Usage example
prefix = "data/era5_labeled_regridded"
sync_s3_to_local(bucket,prefix,  DATA_DIR)


Skipping data/era5_labeled_regridded/2018-01-01.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-02.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-03.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-04.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-05.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-06.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-07.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-08.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-09.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-10.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-11.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-12.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-13.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-14.nc (already exists)
Skipping data/era5_labeled_regridded/2018-01-15.

In [170]:
import glob
source_directory = '/home/ec2-user/SageMaker/data_downloads/data/era5_labeled_regridded'
train_directory = f'{MODEL_DATA}/train'
val_directory = f'{MODEL_DATA}/val'
test_directory = f'{MODEL_DATA}/test'

%mkdatadir $train_directory
%mkdatadir $val_directory
%mkdatadir $test_directory


val_pattern = '2018-12-*.nc'
test_pattern = '2018-11-*.nc'
print(MODEL_DATA, train_directory)
# Get the list of files in the source directory matching the pattern
# val and test should not overlap
val_files = glob.glob(os.path.join(source_directory, file_pattern))
test_files = glob.glob(os.path.join(source_directory, test_pattern))
train_files = [f for f in all_files if f not in val_files and f not in test_files]
# Create symbolic links for each file in the target directory

n_train, n_val, n_test = 1, 1, 1

train_files=train_files[0:n_train]
val_files=val_files[0:n_val]
test_files=test_files[0:n_test]


# Iterate over the files and remove symbolic links
print("unlinking existing files")
for directory in [train_directory, val_directory, test_directory]:
    for file in os.listdir(directory):
        file_path = os.path.join(directory, file)
        if os.path.islink(file_path):
            os.unlink(file_path)

print("linking downloads to model data")
for file in train_files:
    source_path = file
    target_path = os.path.join(train_directory, os.path.basename(file))
    os.symlink(source_path, target_path)

for file in val_files:
    source_path = file
    target_path = os.path.join(val_directory, os.path.basename(file))
    os.symlink(source_path, target_path)

for file in test_files:
    source_path = file
    target_path = os.path.join(test_directory, os.path.basename(file))
    os.symlink(source_path, target_path)


print("done")
! echo Training files && ls $train_directory
print()
! echo Validation files && ls $val_directory
print()
! echo Test files && ls $test_directory

/home/ec2-user/SageMaker/model_data /home/ec2-user/SageMaker/model_data/train
unlinking existing files
linking downloads to model data
done
Training files
2018-01-01.nc

Validation files
2018-12-08.nc

Test files
2018-11-18.nc


In [175]:
%cd $HOME/SageMaker/ClimateNet
%pwd
JACCARD_PATH = "./models/Baseline"
%ls $JACCARD_PATH
%cat $JACCARD_PATH/config.json

/home/ec2-user/SageMaker/ClimateNet
config.json  history.csv  weights.pth
{
    "architecture": "cgnet",
    "seed": 42,
    "lr": 0.001,
    "train_batch_size": 4,
    "pred_batch_size": 8,
    "epochs": 15,
    "fields": {
        "TMQ": {
            "mean": 19.21859,
            "std": 15.81723
        },
        "U850": {
            "mean": 1.55302,
            "std": 8.29764
        },
        "V850": {
            "mean": 0.25413,
            "std": 6.23163
        },
        "PSL": {
            "mean": 100814.414,
            "std": 1461.2227
        }
    },
    "labels": [
        "Background",
        "Tropical Cyclone",
        "Atmospheric River"
    ],
    "loss": "jaccard",
    "scheduler": false,
    "description": "Baseline: CGNet with jaccard loss trained on original ClimateNet with no learning rate scheduling."
}

In [176]:
import train_eval 
model_path = f"{HOME}/SageMaker/ClimateNet/{JACCARD_PATH}/"
predictions = train_eval.run(model_path, MODEL_DATA)

# !python3 train_eval.py \
# -d $MODEL_DATA \
# -m $HOME/SageMaker/ClimateNet/$JACCARD_PATH/


================ Training epoch #1 (cuda:0) ================


Loss: 0.88028 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:01<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.88028 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.88028 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.42702956 0.00070775 0.        ]  | Mean:  0.14257910595743686
Dice score:   [0.59848734 0.00141451 0.        ]  | Mean:  0.19996728233561287
Precision:    [9.98893993e-01 7.10408911e-04 0.00000000e+00]
Recall:       [0.42723157 0.15923567        nan]
Specificity:  [0.26509993 0.85582275 0.57161642]
Sensitivity:  [0.42723157 0.15923567        nan]
[[4.270e+01 1.441e+01 4.283e+01]
 [4.700e-02 1.000e-02 7.000e-03]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.79it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:61: RuntimeWarning: invalid value encountered in divide
  precision = true_positives / (true_positives + false_positives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.90516 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [1.67978668e-01 3.92403769e-04 1.00000000e+00]  | Mean:  0.389457023932954
Dice score:   [2.87639959e-01 7.84499698e-04 1.00000000e+00]  | Mean:  0.4294748195301074
Precision:    [9.99985697e-01 3.92404902e-04            nan]
Recall:       [0.16797907 0.99269759        nan]
Specificity:  [0.26509993 0.85582275 0.57161642]
Sensitivity:  [0.42723157 0.15923567        nan]
[[1.679e+01 8.317e+01 0.000e+00]
 [0.000e+00 3.300e-02 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #2 (cuda:0) ================


Loss: 0.87414 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.87414 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.87414 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [5.57333812e-01 4.50843992e-05 0.00000000e+00]  | Mean:  0.18579296542951718
Dice score:   [7.15753819e-01 9.01647334e-05 0.00000000e+00]  | Mean:  0.23861466134315282
Precision:    [9.99110869e-01 4.53338594e-05 0.00000000e+00]
Recall:       [0.55761038 0.00812651        nan]
Specificity:  [0.22907973 0.88461878 0.67305982]
Sensitivity:  [0.55761038 0.00812651        nan]
[[5.573e+01 1.153e+01 3.268e+01]
 [5.000e-02 1.000e-03 1.400e-02]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.79it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.91173 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.08325419 0.00034607 0.        ]  | Mean:  0.027866751930992476
Dice score:   [0.15371127 0.0006919  0.        ]  | Mean:  0.05146772178298025
Precision:    [1.00000000e+00 3.46080325e-04 0.00000000e+00]
Recall:       [0.08325419 0.90764605        nan]
Specificity:  [0.22907973 0.88461878 0.67305982]
Sensitivity:  [0.55761038 0.00812651        nan]
[[8.323e+00 8.623e+01 5.412e+00]
 [0.000e+00 3.000e-02 3.000e-03]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #3 (cuda:0) ================


Loss: 0.86378 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.86378 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.86378 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [7.3979389e-01 1.8122845e-04 0.0000000e+00]  | Mean:  0.24665837277782465
Dice score:   [8.50438542e-01 3.62391225e-04 0.00000000e+00]  | Mean:  0.28360031120395723
Precision:    [9.99153711e-01 1.83132553e-04 0.00000000e+00]
Recall:       [0.74025774 0.01713156        nan]
Specificity:  [0.02591698 0.93979601 0.80058444]
Sensitivity:  [0.74025774 0.01713156        nan]
[[7.398e+01 6.017e+00 1.994e+01]
 [6.300e-02 1.000e-03 1.000e-03]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.79it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.91427 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.03586105 0.00024728 0.        ]  | Mean:  0.012036108116620684
Dice score:   [0.06923911 0.00049443 0.        ]  | Mean:  0.023244513122162757
Precision:    [1.00000000e+00 2.47352573e-04 0.00000000e+00]
Recall:       [0.03586105 0.44372852        nan]
Specificity:  [0.02591698 0.93979601 0.80058444]
Sensitivity:  [0.74025774 0.01713156        nan]
[[3.585e+00 5.899e+01 3.739e+01]
 [0.000e+00 1.500e-02 1.800e-02]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #4 (cuda:0) ================


Loss: 0.85401 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.85401 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.76it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.85401 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [8.08103040e-01 3.99523768e-06 0.00000000e+00]  | Mean:  0.26936901167635735
Dice score:   [8.93868349e-01 7.99044343e-06 0.00000000e+00]  | Mean:  0.2979587799218773
Precision:    [9.99204782e-01 4.06924223e-06 0.00000000e+00]
Recall:       [8.08623089e-01 2.19635405e-04            nan]
Specificity:  [2.19635405e-04 9.65257548e-01 8.43466300e-01]
Sensitivity:  [8.08623089e-01 2.19635405e-04            nan]
[[8.081e+01 3.472e+00 1.565e+01]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.83it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.91357 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.03492854 0.00037765 0.        ]  | Mean:  0.011768730924818269
Dice score:   [0.06749943 0.00075501 0.        ]  | Mean:  0.022751481243810646
Precision:    [1.00000000e+00 3.77877264e-04 0.00000000e+00]
Recall:       [0.03492854 0.38573883        nan]
Specificity:  [2.19635405e-04 9.65257548e-01 8.43466300e-01]
Sensitivity:  [8.08623089e-01 2.19635405e-04            nan]
[[3.492e+00 3.356e+01 6.291e+01]
 [0.000e+00 1.300e-02 2.000e-02]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #5 (cuda:0) ================


Loss: 0.84580 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.84580 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.84580 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.83698838 0.         0.        ]  | Mean:  0.27899612615137925
Dice score:   [0.91126148 0.         0.        ]  | Mean:  0.30375382819368735
Precision:    [0.99923204 0.         0.        ]
Recall:       [0.83752714 0.                nan]
Specificity:  [0.         0.9749346  0.86268093]
Sensitivity:  [0.83752714 0.                nan]
[[8.370e+01 2.505e+00 1.373e+01]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.84it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.91179 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.06825594 0.00075807 0.        ]  | Mean:  0.023004671701111177
Dice score:   [0.12778949 0.001515   0.        ]  | Mean:  0.043101496677187184
Precision:    [1.00000000e+00 7.58629652e-04 0.00000000e+00]
Recall:       [0.06825594 0.50902062        nan]
Specificity:  [0.         0.9749346  0.86268093]
Sensitivity:  [0.83752714 0.                nan]
[[6.823e+00 2.205e+01 7.109e+01]
 [0.000e+00 1.700e-02 1.600e-02]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #6 (cuda:0) ================


Loss: 0.83956 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.83956 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.83956 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.85009257 0.         0.        ]  | Mean:  0.2833641899956597
Dice score:   [0.91897301 0.         0.        ]  | Mean:  0.30632433705482537
Precision:    [0.99924387 0.         0.        ]
Recall:       [0.85063976 0.                nan]
Specificity:  [0.         0.97780835 0.87291322]
Sensitivity:  [0.85063976 0.                nan]
[[8.501e+01 2.218e+00 1.271e+01]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.86it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.90906 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.13055786 0.00103545 0.        ]  | Mean:  0.043864438611092425
Dice score:   [0.23096184 0.00206876 0.        ]  | Mean:  0.07767686822515187
Precision:    [1.         0.00103627 0.        ]
Recall:       [0.13055786 0.56658076        nan]
Specificity:  [0.         0.97780835 0.87291322]
Sensitivity:  [0.85063976 0.                nan]
[[1.305e+01 1.796e+01 6.895e+01]
 [0.000e+00 1.900e-02 1.400e-02]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #7 (cuda:0) ================


Loss: 0.83538 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.83538 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.79it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.83538 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.85694278 0.         0.        ]  | Mean:  0.2856475924268181
Dice score:   [0.92296089 0.         0.        ]  | Mean:  0.3076536293112458
Precision:    [0.99924991 0.         0.        ]
Recall:       [0.85749438 0.                nan]
Specificity:  [0.         0.97826004 0.87931202]
Sensitivity:  [0.85749438 0.                nan]
[[8.569e+01 2.173e+00 1.207e+01]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.85it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.90508 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.21706014 0.00127606 0.        ]  | Mean:  0.07277873410574359
Dice score:   [0.35669584 0.00254886 0.        ]  | Mean:  0.11974823392089173
Precision:    [0.99993424 0.00127731 0.        ]
Recall:       [0.21706324 0.56572165        nan]
Specificity:  [0.         0.97826004 0.87931202]
Sensitivity:  [0.85749438 0.                nan]
[[2.170e+01 1.455e+01 6.372e+01]
 [1.000e-03 1.900e-02 1.300e-02]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #8 (cuda:0) ================


Loss: 0.83224 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.83224 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.83224 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.86188366 0.         0.        ]  | Mean:  0.2872945526499807
Dice score:   [0.92581903 0.         0.        ]  | Mean:  0.3086063422097073
Precision:    [0.9992542 0.        0.       ]
Recall:       [0.86243844 0.                nan]
Specificity:  [0.         0.97641452 0.88609724]
Sensitivity:  [0.86243844 0.                nan]
[[8.619e+01 2.357e+00 1.139e+01]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.83it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.90026 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [3.20261708e-01 2.74743584e-04 0.00000000e+00]  | Mean:  0.10684548402243003
Dice score:   [0.48514883 0.00054934 0.        ]  | Mean:  0.16189938718231442
Precision:    [9.99080565e-01 2.75540339e-04 0.00000000e+00]
Recall:       [0.32035613 0.08676976        nan]
Specificity:  [0.         0.97641452 0.88609724]
Sensitivity:  [0.86243844 0.                nan]
[[3.202e+01 1.036e+01 5.759e+01]
 [2.900e-02 3.000e-03 1.000e-03]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #9 (cuda:0) ================


Loss: 0.82998 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.82998 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.82998 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.86632171 0.         0.        ]  | Mean:  0.2887739016685957
Dice score:   [0.92837339 0.         0.        ]  | Mean:  0.3094577970068673
Precision:    [0.99925802 0.         0.        ]
Recall:       [0.86687934 0.                nan]
Specificity:  [0.         0.97240015 0.89454707]
Sensitivity:  [0.86687934 0.                nan]
[[8.663e+01 2.758e+00 1.054e+01]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.86it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.89487 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.42657216 0.         0.        ]  | Mean:  0.1421907212999132
Dice score:   [0.59803797 0.         0.        ]  | Mean:  0.19934599159879085
Precision:    [0.99922954 0.         0.        ]
Recall:       [0.42671251 0.                nan]
Specificity:  [0.         0.97240015 0.89454707]
Sensitivity:  [0.86687934 0.                nan]
[[4.266e+01 6.911e+00 5.040e+01]
 [3.300e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #10 (cuda:0) ================


Loss: 0.82832 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.82832 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.82832 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.87076187 0.         0.        ]  | Mean:  0.2902539571126302
Dice score:   [0.93091685 0.         0.        ]  | Mean:  0.3103056156527851
Precision:    [0.9992618 0.        0.       ]
Recall:       [0.87132237 0.                nan]
Specificity:  [0.         0.9683223  0.90306247]
Sensitivity:  [0.87132237 0.                nan]
[[8.708e+01 3.166e+00 9.694e+00]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.89it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.88927 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.50571611 0.         0.        ]  | Mean:  0.1685720373083044
Dice score:   [0.67172837 0.         0.        ]  | Mean:  0.22390945540564253
Precision:    [0.99935003 0.         0.        ]
Recall:       [0.5058825 0.              nan]
Specificity:  [0.         0.9683223  0.90306247]
Sensitivity:  [0.87132237 0.                nan]
[[5.057e+01 5.175e+00 4.422e+01]
 [3.300e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #11 (cuda:0) ================


Loss: 0.82698 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.82698 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.79it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.82698 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.87507771 0.         0.        ]  | Mean:  0.29169256893205053
Dice score:   [0.93337754 0.         0.        ]  | Mean:  0.3111258460114174
Precision:    [0.99926544 0.         0.        ]
Recall:       [0.87564098 0.                nan]
Specificity:  [0.         0.96617494 0.90952428]
Sensitivity:  [0.87564098 0.                nan]
[[8.751e+01 3.380e+00 9.048e+00]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.83it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.88349 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.56985756 0.         0.        ]  | Mean:  0.18995252067660107
Dice score:   [0.72599907 0.         0.        ]  | Mean:  0.24199968872461933
Precision:    [0.99942315 0.         0.        ]
Recall:       [0.57004506 0.                nan]
Specificity:  [0.         0.96617494 0.90952428]
Sensitivity:  [0.87564098 0.                nan]
[[5.699e+01 4.126e+00 3.885e+01]
 [3.300e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #12 (cuda:0) ================


Loss: 0.82588 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.82588 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.82588 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.8795207 0.        0.       ]  | Mean:  0.2931735662766445
Dice score:   [0.93589892 0.         0.        ]  | Mean:  0.311966307643385
Precision:    [0.99926915 0.         0.        ]
Recall:       [0.88008683 0.                nan]
Specificity:  [0.         0.96293516 0.91720496]
Sensitivity:  [0.88008683 0.                nan]
[[8.795e+01 3.704e+00 8.280e+00]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.89it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.87729 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.63460513 0.         0.        ]  | Mean:  0.21153504171489199
Dice score:   [0.77646291 0.         0.        ]  | Mean:  0.2588209696163401
Precision:    [0.99948198 0.         0.        ]
Recall:       [0.63481392 0.                nan]
Specificity:  [0.         0.96293516 0.91720496]
Sensitivity:  [0.88008683 0.                nan]
[[6.346e+01 3.689e+00 3.282e+01]
 [3.300e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #13 (cuda:0) ================


Loss: 0.82495 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.82495 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.80it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.82495 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.88371362 0.         0.        ]  | Mean:  0.2945712054217303
Dice score:   [0.93826748 0.         0.        ]  | Mean:  0.31275582750818776
Precision:    [0.99927261 0.         0.        ]
Recall:       [0.88428245 0.                nan]
Specificity:  [0.         0.95895797 0.92537251]
Sensitivity:  [0.88428245 0.                nan]
[[8.837e+01 4.102e+00 7.463e+00]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.88it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.87073 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.69703844 0.         0.        ]  | Mean:  0.23234614619502314
Dice score:   [0.82147631 0.         0.        ]  | Mean:  0.27382543719957825
Precision:    [0.99952835 0.         0.        ]
Recall:       [0.69726778 0.                nan]
Specificity:  [0.         0.95895797 0.92537251]
Sensitivity:  [0.88428245 0.                nan]
[[6.970e+01 3.234e+00 2.703e+01]
 [3.300e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #14 (cuda:0) ================


Loss: 0.82414 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.82414 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.82414 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.88795711 0.         0.        ]  | Mean:  0.29598570458682966
Dice score:   [0.9406539 0.        0.       ]  | Mean:  0.31355130095860767
Precision:    [0.99927609 0.         0.        ]
Recall:       [0.88852868 0.                nan]
Specificity:  [0.         0.95435505 0.93421597]
Sensitivity:  [0.88852868 0.                nan]
[[8.880e+01 4.562e+00 6.578e+00]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.83it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.86407 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.74534225 0.         0.        ]  | Mean:  0.24844741821289062
Dice score:   [0.85409295 0.         0.        ]  | Mean:  0.28469764890247873
Precision:    [0.99955891 0.         0.        ]
Recall:       [0.74558749 0.                nan]
Specificity:  [0.         0.95435505 0.93421597]
Sensitivity:  [0.88852868 0.                nan]
[[7.453e+01 2.816e+00 2.262e+01]
 [3.300e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

================ Training epoch #15 (cuda:0) ================


Loss: 0.82337 (jaccard) | LR: 0.001:   0%|          | 0/1 [00:00<?, ?it/s]/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'minibatch_loss': train_loss.item()}, ignore_index=True)
Loss: 0.82337 (jaccard) | LR: 0.001: 100%|██████████| 1/1 [00:00<00:00,  1.77it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:137: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instea


Training loss: 0.82337 (jaccard) 
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.89204082 0.         0.        ]  | Mean:  0.29734693927529415
Dice score:   [0.94294035 0.         0.        ]  | Mean:  0.3143134508239324
Precision:    [0.9992794 0.        0.       ]
Recall:       [0.89261501 0.                nan]
Specificity:  [0.         0.9500093  0.94264264]
Sensitivity:  [0.89261501 0.                nan]
[[8.920e+01 4.996e+00 5.736e+00]
 [6.400e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Validation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.81it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/models.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  history = history.append({'epoch_val_loss': val_loss, 'learning_rate': self.optimizer.param_groups[0]["lr"],\



Validation loss: 0.85758 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.77750171 0.         0.        ]  | Mean:  0.2591672355746046
Dice score:   [0.87482527 0.         0.        ]  | Mean:  0.29160842388420133
Precision:    [0.99957714 0.         0.        ]
Recall:       [0.77775752 0.                nan]
Specificity:  [0.         0.9500093  0.94264264]
Sensitivity:  [0.89261501 0.                nan]
[[7.775e+01 2.367e+00 1.985e+01]
 [3.300e-02 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]]

---------- Evaluation (cuda:0) ----------


100%|██████████| 1/1 [00:00<00:00,  2.84it/s]
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:62: RuntimeWarning: invalid value encountered in divide
  recall = true_positives / (true_positives + false_negatives)
/home/ec2-user/SageMaker/ClimateNet/climatenet/utils/metrics.py:64: RuntimeWarning: invalid value encountered in divide
  sensitivity = true_positives / (true_positives + false_negatives)



Test loss: 1.71749 (jaccard)
Classes:      [    BG         TCs        ARs   ]
IoUs:         [0.77015531 0.         0.        ]  | Mean:  0.25671843540521316
Dice score:   [0.87015563 0.         0.        ]  | Mean:  0.29005187793837545
Precision:    [0.99796656 0.         0.        ]
Recall:       [0.77136577 0.                nan]
Specificity:  [0.         0.97164041 0.80003964]
Sensitivity:  [0.77136577 0.                nan]
[[77.016  2.832 19.996]
 [ 0.157  0.     0.   ]
 [ 0.     0.     0.   ]]


100%|██████████| 1/1 [00:00<00:00,  2.81it/s]

[<xarray.DataArray (time: 8, lat: 768, lon: 1152)>
array([[[2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        ...,
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2]],

       [[2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        ...,
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2]],

       [[2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        ...,
...
        ...,
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2]],

       [[2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        ...,
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2]],

       [[2, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],
        [2, 2,

In [190]:
# predictions.to_netcdf("predictions.nc")
# print("done")
ds = predictions.to_dataset(name="predictions")
ds.to_netcdf("predictions.nc")


In [ ]:
# TODO run this w cartopy
# predictions.plot()
p = predictions.isel(time=0).plot(
    subplot_kws=dict(projection=ccrs.Orthographic(-80, 35), facecolor="gray"),
    transform=ccrs.PlateCarree(),
)
p.axes.coastlines()
p.axes.gridlines()
plt.draw()